### ISSUE TITLE
Dockerfile + docker-compose.yaml

### ISSUE THREAD

**Issue by AlexDyakonov** [shampsdev/kvizik-backend#3]
Написать Dockerfile для нашего сервиса. Должен запускаться бекенд. Там сейчас есть сваггер и пара эндпоинтов.\
\
Так же docker-compose.yaml, он скорее всего будет выглядит очень просто, типа так:

```
services:
  app:
    container_name: app
    build: .
    ports:
      - "8000:8000"
    restart: unless-stopped
```

Должно работать:

`docker compose up --build`

<sub><a href="https://huly.app/guest/shampsmini?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzAzYmJhOGI5ODBmNDFkYjY2YzVhYjMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHViYWxleGR5LXNoYW1wc21pbmktNjcwM2I2NjYtMWY1MGQzMmI1OS1kYTVlYmMifQ.aprJCiPKfUhYn5dTQgwHC1wEY_nU2LVuCJcykz1rt28">Huly&reg;: <b>KVK-3</b></a></sub>
